import { Item } from "./Order";
import { OrderType } from "./order-type";

export const listItems: Item[] = [
  {
    name: "Red Potion",
    price: 10,
    image: "/potion/red-potion.png",
    type: OrderType.Usableitems,
  },
  {
    name: "Orange Potion",
    price: 20,
    image: "/potion/orange-potion.png",
    type: OrderType.Usableitems,
  },
  {
    name: "Yellow Potion",
    price: 30,
    image: "/potion/yellow-potion.png",
    type: OrderType.Usableitems,
  },
  {
    name: "White Potion",
    price: 60,
    image: "/potion/white-potion.png",
    type: OrderType.Usableitems,
  },
  {
    name: "Blue Potion",
    price: 40,
    image: "/potion/blue-potion.png",
    type: OrderType.Usableitems,
  },
  {
    name: "Green Potion",
    price: 50,
    image: "/potion/green-potion.png",
    type: OrderType.Usableitems,
  },
  {
    name: "Concentration Potion",
    price: 100,
    image: "/potion/concentration-potion.png",
    type: OrderType.Usableitems,
  },
  {
    name: "Awakening Potion",
    price: 200,
    image: "/potion/awakening-potion.png",
    type: OrderType.Usableitems,
  },
  {
    name: "Berserk Potion",
    price: 300,
    image: "/potion/berserk-potion.png",
    type: OrderType.Usableitems,
  },
  {
    name: "Small Life Potion",
    price: 100,
    image: "/potion/small-life-potion.png",
    type: OrderType.Usableitems,
  },
  {
    name: "Medium Life Potion",
    price: 200,
    image: "/potion/medium-life-potion.png",
    type: OrderType.Usableitems,
  },
  {
    name: "Big Defense Potion",
    price: 300,
    image: "/potion/big-defense-potion.png",
    type: OrderType.Usableitems,
  },
  {
    name: "Pole Axe",
    price: 500,
    image: "/spear/pole-axe.png",
    type: OrderType.Weapon,
  },
  {
    name: "Long Horn",
    price: 600,
    image: "/spear/long-horn.png",
    type: OrderType.Weapon,
  },
  {
    name: "Thanatos spear",
    price: 700,
    image: "/spear/thanos-spear.png",
    type: OrderType.Weapon,
  },
  {
    name: "Adulter Fides Guardian Spear",
    price: 800,
    image: "/spear/adulter-fides-guardian-spear.png",
    type: OrderType.Weapon,
  },
  {
    name: "Dagger",
    price: 300,
    image: "/dagger/dagger.png",
    type: OrderType.Weapon,
  },
  {
    name: "Damascus",
    price: 400,
    image: "/dagger/damascus.png",
    type: OrderType.Weapon,
  },
  {
    name: "Combat Knife",
    price: 500,
    image: "/dagger/combat-knife.png",
    type: OrderType.Weapon,
  },
  {
    name: "Assasin Dagger",
    price: 600,
    image: "/dagger/assasin-dagger.png",
    type: OrderType.Weapon,
  },
  {
    name: "Swords",
    price: 1000,
    image: "/sword/swords.png",
    type: OrderType.Weapon,
  },
  {
    name: "Falchion",
    price: 1100,
    image: "/sword/falchion.png",
    type: OrderType.Weapon,
  },
  {
    name: "Blade",
    price: 1200,
    image: "/sword/blade.png",
    type: OrderType.Weapon,
  },
  {
    name: "Adulter Fidews Guardian Sword",
    price: 1300,
    image: "/sword/adulter-fides-guardian.png",
    type: OrderType.Weapon,
  },
  {
    name: "Swords",
    price: 1000,
    image: "/sword2/swords.png",
    type: OrderType.Weapon,
  },
  {
    name: "Broad",
    price: 1100,
    image: "/sword2/broad.png",
    type: OrderType.Weapon,
  },
  {
    name: "Claymore",
    price: 1200,
    image: "/sword2/claymore.png",
    type: OrderType.Weapon,
  },
  {
    name: "Muramasa",
    price: 1300,
    image: "/sword2/muramasa.png",
    type: OrderType.Weapon,
  },
  {
    name: "Shirt",
    price: 100,
    image: "/shirt/shirt.png",
    type: OrderType.Armor,
  },
  {
    name: "Adventure Suit",
    price: 200,
    image: "/shirt/adventure-suit.png",
    type: OrderType.Armor,
  },
  {
    name: "Assassin Robe",
    price: 300,
    image: "/shirt/assassin-robe.png",
    type: OrderType.Armor,
  },
  {
    name: "Chain Mail",
    price: 400,
    image: "/shirt/chain-mail.png",
    type: OrderType.Armor,
  },
  {
    name: "Angel Spirit",
    price: 1000,
    image: "/head/angel-spirit.png",
    type: OrderType.Armor,
  },
  {
    name: "Angel Wing",
    price: 2000,
    image: "/head/angel-wing.png",
    type: OrderType.Armor,
  },
  {
    name: "Angel Wing Ears",
    price: 3000,
    image: "/head/angel-wing-ears.png",
    type: OrderType.Armor,
  },
  {
    name: "Baphomet Horns",
    price: 4000,
    image: "/head/baphomet-horns.png",
    type: OrderType.Armor,
  },
  {
    name: "Hood",
    price: 100,
    image: "/garment/hood.png",
    type: OrderType.Armor,
  },
  {
    name: "Clock Of Survival",
    price: 200,
    image: "/garment/clock-of-survival.png",
    type: OrderType.Armor,
  },
  {
    name: "Diablo Healinium",
    price: 300,
    image: "/garment/diablo-healinium.png",
    type: OrderType.Armor,
  },
  {
    name: "Abysmal Knight Card",
    price: 5000,
    image: "/card/abysmal-knight.png",
    type: OrderType.Card,
  },
  {
    name: "Alice Card",
    price: 3000,
    image: "/card/alice.png",
    type: OrderType.Card,
  },
  {
    name: "Andre Card",
    price: 500,
    image: "/card/andre.png",
    type: OrderType.Card,
  },
];
